backend:
  demoData: false
  image:
    repository: cxtsiacr.azurecr.io/backstage
    tag: 0.1.3
  postgresCertMountEnabled: false

lighthouse:
  enabled: false

ingress:
  enabled: true

postgresql:
  enabled: true

appConfig:
  app:
    baseUrl: https://cxtsidevopstoolsbackstage.germanywestcentral.cloudapp.azure.com
    title: Backstage - Catena-X
    support:
      url: https://github.com/catenax/DevOpsTools/issues
      items:
        - title: Issues
          icon: github
          links:
            - url: https://github.com/catenax/DevOpsTools/issues
              title: GitHub Issues
  backend:
    auth:
      keys:
        - secret: ${BACKEND_SECRET}
    baseUrl: https://cxtsidevopstoolsbackstage.germanywestcentral.cloudapp.azure.com
    cors:
      origin: https://cxtsidevopstoolsbackstage.germanywestcentral.cloudapp.azure.com
    database:
      client: pg
      connection:
        host: ${PG_HOST}
        port: ${PG_PORT}
        user: ${PG_USER}
        password: ${PG_PASS}
        database: ${PG_DB}
  lighthouse:
    baseUrl: https://cxtsidevopstoolsbackstage.germanywestcentral.cloudapp.azure.com/lighthouse-api
  techdocs:
    storageUrl: https://cxtsidevopstoolsbackstage.germanywestcentral.cloudapp.azure.com/api/techdocs/static/docs
    requestUrl: https://cxtsidevopstoolsbackstage.germanywestcentral.cloudapp.azure.com/api/techdocs

token_github: token_github
auth_github_client_id: auth_github_client_id
auth_github_client_secret: auth_github_client_secret
pg_host: pg_host
pg_port: pg_port
pg_user: pg_user
pg_pass: pg_pass
pg_db: pg_db
backend_secret: backend_secret
cxtsi_acr_docker_config: cxtsi_acr_docker_config

dockerRegistrySecretName: backstage-regcred