# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: ${ secrets.POSTGRES_USER }
  POSTGRES_PASSWORD: ${ secrets.POSTGRES_PASSWORD }
