apiVersion: v1
kind: Service
metadata:
  name: prometheus-server 
  namespace: default
spec:
  type: ExternalName
  externalName: prometheus-server.monitoring.svc.cluster.local
  ports:
  - port: 80

