apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend 
  namespace: default
spec:
  type: ExternalName
  externalName: thanos-query-frontend.monitoring.svc.cluster.local
  ports:
  - port: 80
