# backstage ingress config (controller and class deployed with terraform)
{{- if .Values.ingress.enabled }}
{{- $frontendUrl := urlParse .Values.appConfig.app.baseUrl}}
{{- $backendUrl := urlParse .Values.appConfig.backend.baseUrl}}
{{- $lighthouseUrl := urlParse .Values.appConfig.lighthouse.baseUrl}}
{{/* Determine the api type for the ingress */}}
{{- if lt .Capabilities.KubeVersion.Minor "19" }}
apiVersion: networking.k8s.io/v1beta1
{{- else if ge .Capabilities.KubeVersion.Minor "19" }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($scheme = https) {
      add_header  Strict-Transport-Security "max-age=0;";
      }
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: {{ include "backstage.fullname" . }}-ingress
spec:
  ingressClassName: backstage
  tls:
  - hosts:
        - {{ $frontendUrl.host }}
        {{- if not ( eq $frontendUrl.host $backendUrl.host ) }}
        - {{ $backendUrl.host }}
        {{- end }}
        {{- if not ( eq $frontendUrl.host $lighthouseUrl.host ) }}
        - {{ $lighthouseUrl.host }}
        {{- end }}
    secretName: backstage-tls
  rules:
    - host: {{ $frontendUrl.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.serviceName" . }}
                port:
                  number: 80
          {{/* Route the backend inside the same hostname as the frontend when they are the same */}}
          {{- if eq $frontendUrl.host $backendUrl.host}}
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.serviceName" . }}
                port:
                  number: 80
          {{/* Route the backend through a different host */}}
          {{- else -}}
    - host: {{ $backendUrl.host }}
      http:
        paths:
          - path: {{ $backendUrl.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.serviceName" . }}
                port:
                  number: 80
         {{- end }}
{{/* Route lighthouse through a different host */}}
{{- if not ( eq $frontendUrl.host $lighthouseUrl.host ) }}
    - host: {{ $lighthouseUrl.host }}
      http:
        paths:
          - path: {{ $lighthouseUrl.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "lighthouse.serviceName" . }}
                port:
                  number: 80
{{- else }}
{{/* Route lighthouse by path with re-write rules when it is hosted under the same hostname */}}
---
{{/* Determine the api type for the ingress */}}
{{- if lt .Capabilities.KubeVersion.Minor "19" }}
apiVersion: networking.k8s.io/v1beta1
{{- else if ge .Capabilities.KubeVersion.Minor "19" }}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "backstage.fullname" . }}-ingress-lighthouse
  annotations:
    {{- if .Values.issuer.email }}
    cert-manager.io/cluster-issuer: {{ .Values.issuer.clusterIssuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($scheme = https) {
      add_header  Strict-Transport-Security "max-age=0;";
      }
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
    - secretName: {{ include "backstage.fullname" . }}-tls
      hosts:
        - {{ $lighthouseUrl.host }}
  rules:
    - host: {{ $lighthouseUrl.host }}
      http:
        paths:
          - path: {{$lighthouseUrl.path}}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "lighthouse.serviceName" . }}
                port:
                  number: 80
{{- end }}
{{- end }}
---
# backstage secrets:
# - github token and oauth application credentials
# - postgresql connection settings and credentials
# - backend secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-secrets
type: Opaque
data:
  GITHUB_TOKEN: {{ .Values.token_github | b64enc }}
  AUTH_GITHUB_CLIENT_ID: {{ .Values.auth_github_client_id | b64enc }}
  AUTH_GITHUB_CLIENT_SECRET: {{ .Values.auth_github_client_secret | b64enc }}
  PG_HOST: { .Values.pg_host | b64enc }}
  PG_PORT: {{ .Values.pg_port | b64enc }}
  PG_USER: {{ .Values.pg_user | b64enc }}
  PG_PASS: {{ .Values.pg_pass | b64enc }}
  PG_DB: {{ .Values.pg_db | b64enc }}
  BACKEND_SECRET: {{ .Values.backend_secret | b64enc }}
---
# backstage registry credetials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backstage.fullname" . }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.cxtsi_acr_docker_config | b64enc }}
---
# backstage backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backstage.fullname" . }}-backstage
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "backstage.fullname" . }}-backstage
        component: backend
    spec:
      {{- if .Values.dockerRegistrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecretName }} #regcred
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}-backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          name: {{ .Chart.Name }}-backend
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          resources:
          {{- toYaml .Values.backend.resources | nindent 12 }}
          envFrom:
          - secretRef:
              name: {{ include "backstage.fullname" . }}-secrets
---
# backstage backend service
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: {{ include "backstage.fullname" . }}-backstage
    component: backend
  type: {{ .Values.backend.serviceType }}
{{- end }}
