---
# backstage secrets:
# - github token and oauth application credentials
# - postgresql connection settings and credentials
# - backend secret
apiVersion: v1
kind: Secret
metadata:
  name: {{include "backstage.fullname" .}}-secrets
type: Opaque
data:
  GITHUB_TOKEN: {{.Values.token_github | b64enc}}
  AUTH_GITHUB_CLIENT_ID: {{.Values.auth_github_client_id | b64enc}}
  AUTH_GITHUB_CLIENT_SECRET: {{.Values.auth_github_client_secret | b64enc}}
  PG_HOST: {{.Values.pg_host | b64enc}}
  PG_PORT: {{.Values.pg_port | b64enc}}
  PG_USER: {{.Values.pg_user | b64enc}}
  PG_PASS: {{.Values.pg_pass | b64enc}}
  PG_DB: {{.Values.pg_db | b64enc}}
  BACKEND_SECRET: {{.Values.backend_secret | b64enc}}
---
# backstage registry credetials
apiVersion: v1
kind: Secret
metadata:
  name: {{include "backstage.fullname" .}}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.cxtsi_acr_docker_config | b64enc}}
...
