---
# backstage secrets:
# - github token and oauth application credentials
# - postgresql connection settings and credentials
# - backend secret
apiVersion: v1
kind: Secret
metadata:
  name: {{include "backstage.fullname" .}}-secrets
type: Opaque
data:
  GITHUB_TOKEN: {{.Values.token_github}}
  AUTH_GITHUB_CLIENT_ID: {{.Values.auth_github_client_id}}
  AUTH_GITHUB_CLIENT_SECRET: {{.Values.auth_github_client_secret}}
  PG_HOST: {{.Values.pg_host}}
  PG_PORT: {{.Values.pg_port}}
  PG_USER: {{.Values.pg_user}}
  PG_PASS: {{.Values.pg_pass}}
  PG_DB: {{.Values.pg_db}}
  BACKEND_SECRET: {{.Values.backend_secret}}
---
# backstage registry credetials
apiVersion: v1
kind: Secret
metadata:
  name: {{include "backstage.fullname" .}}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.Values.cxtsi_acr_docker_config}}
...
