# backstage backend service
{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.backend.containerPort }}
  selector:
    app: {{ include "backstage.fullname" . }}-backstage
    component: backend
  type: {{ .Values.backend.serviceType }}
{{- end }}