---
# postgresql secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{include "backstage.fullname" .}}-postgres-secrets
type: Opaque
data:
  POSTGRES_USER: {{.Values.pg_user}}
  POSTGRES_PASSWORD: {{.Values.pg_pass}}
...
