on:
  push:
    branches:
      - backstage-deploy
      - test-values

jobs:
  deploy:
    name: Deploy Backstage
    runs-on: ubuntu-latest
    environment: Catena-X dev/int
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kube Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Backstage
        run: |
          echo "Current kube context: $(kubectl config current-context)"
          sed -i "s/PG_HOST/${{ secrets.PG_HOST }}/g" Backstage/backstage-values.yaml
          sed -i "s/PG_PORT/${{ secrets.PG_PORT }}/g" Backstage/backstage-values.yaml
          sed -i "s/PG_USER/${{ secrets.CATENAX_ADMIN_USER }}/g" Backstage/backstage-values.yaml
          sed -i "s/PG_PASS/${{ secrets.CATENAX_ADMIN_PASSWORD }}/g" Backstage/backstage-values.yaml
          sed -i "s/PG_SRV/${{ secrets.PG_SRV }}/g" Backstage/backstage-values.yaml
          helm repo add deliveryhero https://charts.deliveryhero.io
          helm upgrade backstage deliveryhero/backstage \
          --install \
          --wait \
          --namespace=backstage \
          --set=app.name=backstage \
          --values=Backstage/backstage-values.yaml \
          --atomic \
