on:
  push:
    branches:
      - backstage-deploy

jobs:
  deploy:
    name: Deploy Backstage
    runs-on: ubuntu-latest
    environment: Catena-X dev/int
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - run: backstage-values.sh
        working-directory: Backstage

      - name: Deploy Backstage
        uses: deliverybot/helm@latest
        with:
          release: backstage
          namespace: backstage
          chart: deliveryhero/backstage
          repository: https://charts.deliveryhero.io/
          value-files: Backstage/backstage-values.yaml
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
