---
on:
  push:
    paths:
      - '.github/workflows/backstage.yml'
      - 'Backstage/**'
    branches:
      - backstage

env:
  bstag: 0.1.3

jobs:

#  build:
#    name: Build Backstage
#    runs-on: catena-x
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#      - run: |
#          export NODE_OPTIONS="--max-old-space-size=4096"
#          cd Backstage/rel20220104
#
#          yarn install --frozen-lockfile
#          yarn tsc
#          yarn build
#
#          docker build .  \
#          -f packages/backend/Dockerfile \
#          -t cxtsiacr.azurecr.io/backstage:${{ env.bstag }}
#
#          docker login cxtsiacr.azurecr.io \
#          -u ${{ secrets.ACR_USER }} \
#          -p ${{ secrets.ACR_PASS }}
#
#          docker push cxtsiacr.azurecr.io/backstage:${{ env.bstag }}

  deploy:
    name: Deploy Backstage
    runs-on: ubuntu-latest
    environment: Catena-X dev/int
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kube Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}

      - name: Deploy Backstage
        working-directory: Backstage/chart
        run: |
          helm upgrade -i backstage-helmtest . \
          -n backstage-helmtest \
          -f devopstools-values.yaml \
          --create-namespace \
          --atomic \
          --set token_github=${{secrets.TOKEN_GITHUB}} \
          --set auth_github_client_id=${{secrets.AUTH_GITHUB_CLIENT_ID}} \
          --set auth_github_client_secret=${{secrets.AUTH_GITHUB_CLIENT_SECRET}} \
          --set pg_host=${{secrets.PG_HOST}} \
          --set pg_port=${{secrets.PG_PORT}} \
          --set pg_user=${{secrets.$PG_USER}} \
          --set pg_pass=${{secrets.PG_PASS}} \
          --set pg_db=${{secrets.PG_DB}} \
          --set backend_secret=${{secrets.BACKEND_SECRET}} \
          --set cxtsi_acr_docker_config=${{secrets.CXTSI_ACR_DOCKER_CONFIG}} \
          --dry-run
          --debug

#      - name: Deploy Backstage
#        uses: deliverybot/helm@v1
#        with:
#          release: backstage
#          namespace: backstage
#          chart: deliveryhero/backstage
#          repository: https://charts.deliveryhero.io/
#          value-files: Backstage/backstage-values.yaml
#        env:
#          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
...
