---
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of image to deploy'
        required: true
        default: 'v1.3.0'
        type: string

jobs:

  deploy:
    name: Deploy Backstage
    runs-on: ubuntu-latest
    env:
      TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
      AUTH_GITHUB_CLIENT_ID: ${{secrets.AUTH_GITHUB_CLIENT_ID}}
      AUTH_GITHUB_CLIENT_SECRET: ${{secrets.AUTH_GITHUB_CLIENT_SECRET}}
      PG_HOST: ${{secrets.PG_HOST}}
      PG_PORT: ${{secrets.PG_PORT}}
      PG_USER: ${{secrets.PG_USER}}
      PG_PASS: ${{secrets.PG_PASS}}
      PG_PATH: ${{github.sha}}
      PG_DB: ${{secrets.PG_DB}}
      BACKEND_SECRET: ${{secrets.BACKEND_SECRET}}
      CXTSI_ACR_DOCKER_CONFIG: ${{secrets.CXTSI_ACR_DOCKER_CONFIG}}
      IMAGE_TAG: ${{inputs.tag}}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kube Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}

      - name: Deploy Backstage
        working-directory: Backstage/chart
        run: |
          helm upgrade -i backstage-helmtest . \
          -n backstage \
          -f devopstools-values.yaml \
          --create-namespace \
          --atomic \
          --set token_github="$TOKEN_GITHUB" \
          --set auth_github_client_id="$AUTH_GITHUB_CLIENT_ID" \
          --set auth_github_client_secret="$AUTH_GITHUB_CLIENT_SECRET" \
          --set pg_host="$PG_HOST" \
          --set pg_port="$PG_PORT" \
          --set pg_user="$PG_USER" \
          --set pg_pass="$PG_PASS" \
          --set pg_path="$PG_PATH" \
          --set pg_db="$PG_DB" \
          --set backend_secret="$BACKEND_SECRET" \
          --set cxtsi_acr_docker_config="$CXTSI_ACR_DOCKER_CONFIG" \
          --set image_tag="$IMAGE_TAG"

#      - name: Deploy Backstage
#        uses: deliverybot/helm@v1
#        with:
#          release: backstage
#          namespace: backstage
#          chart: deliveryhero/backstage
#          repository: https://charts.deliveryhero.io/
#          value-files: Backstage/backstage-values.yaml
#        env:
#          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
...
