on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Build and deploy Backstage'

env:
  bstag: 0.1.2

jobs:
  build:
    name: Build Backstage
    runs-on: catena-x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          cd Backstage/rel20220104
          yarn install --frozen-lockfile
          yarn tsc
          yarn build
          docker build .  -f packages/backend/Dockerfile -t cxtsiacr.azurecr.io/backstage:${{ env.bstag }}
          docker login cxtsiacr.azurecr.io -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_PASS }}
          docker push cxtsiacr.azurecr.io/backstage:${{ env.bstag }}

#  deploy:
#    name: Deploy Backstage
#    runs-on: ubuntu-latest
#    environment: Catena-X dev/int
#    steps:

#      - name: Checkout repository
#        uses: actions/checkout@v2

#      - name: Set Kube Context
#        uses: azure/k8s-set-context@v1
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.KUBECONFIG }}

#      - name: Deploy Backstage
#        run: |
#          helm upgrade backstage backstage --install --wait --namespace=backstage --set=app.name=backstage --repo=https://charts.deliveryhero.io/ --values=Backstage/backstage-values.yaml --atomic

#      - name: Deploy Backstage
#        uses: deliverybot/helm@v1
#        with:
#          release: backstage
#          namespace: backstage
#          chart: deliveryhero/backstage
#          repository: https://charts.deliveryhero.io/
#          value-files: Backstage/backstage-values.yaml
#        env:
#          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
