on:
  push:
    branches:
      - feature/A1ODT-93

jobs:
  deploy:
    name: Deploy Loki 
    runs-on: ubuntu-latest
    environment: Catena-X dev/int
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kube Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Loki 
        run: |
          helm upgrade --install loki loki-stack --repo=https://grafana.github.io/helm-charts --namespace logging --set grafana.enabled=false,prometheus.enabled=false,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false --atomic 
          
