on:
  push:
    tags:
      - v**

jobs:
  deploy:
    name: Deploy Monitoring Stack 
    runs-on: ubuntu-latest
    environment: Catena-X dev/int
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kube Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Prometheus 
        # manually create storageaccount key secret
        # kubectl -n monitoring create secret generic thanos-objstore-config --from-file=thanos.yaml=thanos.yaml
        run: |
          helm upgrade prometheus kube-prometheus-stack  --install --wait --repo=https://prometheus-community.github.io/helm-charts --namespace=monitoring --values=Prometheus/prometheus.yaml --atomic
          kubectl apply -f Prometheus/kubernetes/externalname.yml
          kubectl apply -f Ingress/ingress-gw.yml
          

      - name: Deploy Thanos 
        run: |
          kubectl apply -f Thanos/kubernetes/querier-deployment.yaml
          kubectl apply -f Thanos/kubernetes/store-statefulset.yaml
          kubectl apply -f Thanos/kubernetes/compactor-statefulset.yaml
          kubectl apply -f Thanos/kubernetes/compactor-service-servicemonitor.yaml
          kubectl apply -f Thanos/kubernetes/store-servicemonitor.yaml
          kubectl apply -f Grafana/kubernetes/externalname.yml
          kubectl apply -f Ingress/ingress-gw.yml
          
