on:
  push:
    branches: [ test-build-push ]
    
env:
  REGISTRY: ghcr.io
  BSTAG: "0.1.2"

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build .  -f packages/backend/Dockerfile -t ${{ env.REGISTRY }}/${{ github.repository }}/backstage:${{ env.BSTAG }}

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push docker image
        run: docker push ${{ env.REGISTRY }}/${{ github.repository }}//backstage:${ env.bstag }
