on:
  push:
    branches:
      - feature/A1ODT-93

jobs:
  deploy:
    name: Deploy Thanos 
    runs-on: ubuntu-latest
    environment: Catena-X dev/int
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Kube Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy Thanos 
        env:
          THANOS_STORAGEACCOUNT_KEY: ${{ secrets.THANOS_STORAGEACCOUNT_KEY }}
        run: |
          # sed -i "s/THANOS_STORAGEACCOUNT_KEY/$THANOS_STORAGEACCOUNT_KEY/g" Thanos/kubernetes/storageaccount.yaml
          
          # kubectl -n monitoring create secret generic thanos-objstore-config -f Thanos/kubernetes/storageaccount.yaml
          kubectl apply -f Thanos/kubernetes/querier-deployment.yaml
          kubectl apply -f Thanos/kubernetes/store-statefulset.yaml
          kubectl apply -f Thanos/kubernetes/compactor-statefulset.yaml
          kubectl apply -f Thanos/kubernetes/compactor-service-servicemonitor.yaml
          kubectl apply -f Thanos/kubernetes/store-servicemonitor.yaml
          kubectl apply -f Grafana/kubernetes/externalname.yml
          kubectl apply -f Ingress/ingress-gw.yml
          
